export const ActionTypes = {
    SAVE_SUBS: 'SAVE_SUBS',
    ADD_SUB: 'ADD_SUB',
    REMOVE_SUB: 'REMOVE_SUB',
    SET_SUBS: 'SET_SUBS',

    CHANGE_SALARY: 'CHANGE_SALARY',
    SAVE_SALARY: 'SAVE_SALARY',
    SET_SALARY: 'SET_SALARY'
}